# ------------------------------------------------------------------------------
# GitHub Actions Workflow - PR Checks
#
# Runs automated checks on pull requests to main branch:
# - Code formatting validation
# - Linting with golangci-lint
# - Unit tests
# - Binary build verification
#
# Triggers on: PR open, PR synchronize (new commits), PR reopen
# ------------------------------------------------------------------------------

name: PR Checks

on:
  pull_request:
    branches: [ main ]

# ------------------------------------------------------------------------------
# Jobs
# ------------------------------------------------------------------------------

jobs:
  pr-checks:
    name: PR Build, Test, and Lint
    runs-on: ubuntu-latest
    
    steps:
    # ------------------------------------------------------------------------------
    # Setup
    # ------------------------------------------------------------------------------
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.1'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    # ------------------------------------------------------------------------------
    # Dependency Management
    # ------------------------------------------------------------------------------
    
    - name: Download dependencies
      run: make deps
    
    # ------------------------------------------------------------------------------
    # Code Quality Checks
    # ------------------------------------------------------------------------------
    
    - name: Format check
      run: |
        make fmt
        git diff --exit-code || (echo "❌ Code is not formatted. Run 'make fmt' locally." && exit 1)
    
    - name: Run linter
      run: make lint
    
    # ------------------------------------------------------------------------------
    # Testing and Build
    # ------------------------------------------------------------------------------
    
    - name: Run tests
      run: make test
    
    - name: Build binary
      run: make build
    
    # ------------------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------------------
    
    - name: PR Check Summary
      if: always()
      run: |
        echo "✅ PR checks complete"
        echo "Branch: ${{ github.head_ref }}"
        echo "Commit: ${{ github.sha }}"
